Parameters:
  DBUsername:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /my-rds-db/username
  DBPassword:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /my-rds-db/password

Resources:
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: my-postgresql-db
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: postgres
      EngineVersion: 13.3
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: STD21033
      BackupRetentionPeriod: 7
      PreferredMaintenanceWindow: 'Sun:01:00-Sun:02:00'

  DBUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref DBUsername
      Type: "String"
      Value: !Ref MyDBInstance.Endpoint.Address
      Description: "Database username"

  DBPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref DBPassword
      Type: "SecureString"
      Value: !Ref MyDBInstance.MasterUserPassword
      Description: "Database password"

  JDBCConnectionString:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /my-rds-db/jdbc-connection-string
      Type: "String"
      Value: !Join
        - ""
        - - "jdbc:postgresql://"
          - !Ref MyDBInstance.Endpoint.Address
          - ":"
          - !Ref MyDBInstance.Endpoint.Port
          - "/"
          - "mydatabase"
      Description: "JDBC connection string for my PostgreSQL RDS instance"

Outputs:
  DatabaseName:
    Value: !Ref MyDBInstance.DBName
    Description: "The name of the PostgreSQL database created in RDS"
